// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_QtQuickUltralite_Profiling();
Q_GHS_KEEP_REFERENCE(qml_register_types_QtQuickUltralite_Profiling)

class QtQuickUltralite_ProfilingPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtQuickUltralite_ProfilingPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_QtQuickUltralite_Profiling;
        Q_UNUSED(registration)
    }
};



#include "QuickUltraLiteStudioProfilingplugin_QtQuickUltralite_ProfilingPlugin.moc"
