// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_Elevia_app();
Q_GHS_KEEP_REFERENCE(qml_register_types_Elevia_app)

class Elevia_appPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    Elevia_appPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_Elevia_app;
        Q_UNUSED(registration)
    }
};



#include "Elevia_appplugin_Elevia_appPlugin.moc"
