// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_QtQuickUltralite_Extras();
Q_GHS_KEEP_REFERENCE(qml_register_types_QtQuickUltralite_Extras)

class QtQuickUltralite_ExtrasPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtQuickUltralite_ExtrasPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_QtQuickUltralite_Extras;
        Q_UNUSED(registration)
    }
};



#include "QuickUltraLiteStudioExtrasplugin_QtQuickUltralite_ExtrasPlugin.moc"
