// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_UntitledProject7();
Q_GHS_KEEP_REFERENCE(qml_register_types_UntitledProject7)

class UntitledProject7Plugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    UntitledProject7Plugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_UntitledProject7;
        Q_UNUSED(registration)
    }
};



#include "UntitledProject7plugin_UntitledProject7Plugin.moc"
