// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_UntitledProject3)
QT_DECLARE_EXTERN_RESOURCE(qmake_UntitledProject3)
QT_DECLARE_EXTERN_RESOURCE(UntitledProject3_raw_qml_0)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_UntitledProject3)

class UntitledProject3Plugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    UntitledProject3Plugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_UntitledProject3)
QT_KEEP_RESOURCE(qmlcache_UntitledProject3)
QT_KEEP_RESOURCE(qmake_UntitledProject3)
QT_KEEP_RESOURCE(UntitledProject3_raw_qml_0)
    }
};



#include "UntitledProject3plugin_UntitledProject3Plugin.moc"
