// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_UntitledProject7Content();
Q_GHS_KEEP_REFERENCE(qml_register_types_UntitledProject7Content)

class UntitledProject7ContentPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    UntitledProject7ContentPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_UntitledProject7Content;
        Q_UNUSED(registration)
    }
};



#include "UntitledProject7Contentplugin_UntitledProject7ContentPlugin.moc"
