
set(target "UntitledProject3Content")
set(working_dir "C:/Users/alrea/Desktop/test/UntitledProject3/UntitledProject3Content")
set(src_and_dest_list
    "C:/Users/alrea/Desktop/test/UntitledProject3/UntitledProject3Content/Icon.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3App-Debug/qml/UntitledProject3Content/Icon.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3/UntitledProject3Content/Main.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3App-Debug/qml/UntitledProject3Content/Main.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3/UntitledProject3Content/HomeForm.ui.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3App-Debug/qml/UntitledProject3Content/HomeForm.ui.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3/UntitledProject3Content/MainForm.ui.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3App-Debug/qml/UntitledProject3Content/MainForm.ui.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3/UntitledProject3Content/Home.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3App-Debug/qml/UntitledProject3Content/Home.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3/UntitledProject3Content/Glassy.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3App-Debug/qml/UntitledProject3Content/Glassy.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3/UntitledProject3Content/App.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3App-Debug/qml/UntitledProject3Content/App.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3/UntitledProject3Content/d3/MouseRotatorAndWASD.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3App-Debug/qml/UntitledProject3Content/d3/MouseRotatorAndWASD.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3/UntitledProject3Content/d3/a_App.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3App-Debug/qml/UntitledProject3Content/d3/a_App.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3/UntitledProject3Content/d3/CustomSwitch.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3App-Debug/qml/UntitledProject3Content/d3/CustomSwitch.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3/UntitledProject3Content/d3/FresnelControls.ui.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3App-Debug/qml/UntitledProject3Content/d3/FresnelControls.ui.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3/UntitledProject3Content/d3/ArcballController.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3App-Debug/qml/UntitledProject3Content/d3/ArcballController.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3/UntitledProject3Content/d3/CustomSlider.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3App-Debug/qml/UntitledProject3Content/d3/CustomSlider.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3/UntitledProject3Content/d3/Screen01Form.ui.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3App-Debug/qml/UntitledProject3Content/d3/Screen01Form.ui.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3/UntitledProject3Content/d3/CustomComboBox.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3App-Debug/qml/UntitledProject3Content/d3/CustomComboBox.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3/UntitledProject3Content/d3/Screen01.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3App-Debug/qml/UntitledProject3Content/d3/Screen01.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3/UntitledProject3Content/d3/SliderText.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3App-Debug/qml/UntitledProject3Content/d3/SliderText.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3/UntitledProject3Content/d3/CustomButton.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3App-Debug/qml/UntitledProject3Content/d3/CustomButton.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3/UntitledProject3Content/d3/Sphere.qml"
    "C:/Users/alrea/Desktop/test/UntitledProject3App-Debug/qml/UntitledProject3Content/d3/Sphere.qml"

)
set(timestamp_file "C:/Users/alrea/Desktop/test/UntitledProject3App-Debug/UntitledProject3Content/.qt/UntitledProject3Content_qml.txt")
