### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Elevia_app)
add_subdirectory(Elevia_appContent)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Elevia_appplugin
    Elevia_appContentplugin
    QtQuickDesignerComponents)