// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_QtQuickUltralite_Layers();
Q_GHS_KEEP_REFERENCE(qml_register_types_QtQuickUltralite_Layers)

class QtQuickUltralite_LayersPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtQuickUltralite_LayersPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_QtQuickUltralite_Layers;
        Q_UNUSED(registration)
    }
};



#include "QuickUltraLiteStudioLayersplugin_QtQuickUltralite_LayersPlugin.moc"
