### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(UntitledProject3)
add_subdirectory(UntitledProject3Content)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    UntitledProject3plugin
    UntitledProject3Contentplugin
    QtQuickDesignerComponents)