// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_Elevia_appContent();
Q_GHS_KEEP_REFERENCE(qml_register_types_Elevia_appContent)

class Elevia_appContentPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    Elevia_appContentPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_Elevia_appContent;
        Q_UNUSED(registration)
    }
};



#include "Elevia_appContentplugin_Elevia_appContentPlugin.moc"
